### ISSUE TITLE
Blacklisted container still being looted

### ISSUE THREAD

**Issue by MysticDaedra** [SteveTownsend/SmartHarvestSE#414] opened 2023-02-05 11:10 UTC
I'm using the latest version of SmartHarvest (5.0.1) and Skyrim SE 1.5.97. I've marked several outdoors containers that are safe as blacklisted, as I use them for storage of various materials: ingredients, ores, etc. Unfortunately despite marking them as such, they continue to be auto-harvested by SmartHarvest. The containers are part of the Riverfall Cottage mod: https://www.nexusmods.com/skyrimspecialedition/mods/34542

**Comment by SteveTownsend** [comment] 2023-02-05 15:02
I'll have a look at some point. I have quite the backlog of work, I am afraid.

**Comment by SteveTownsend** [comment] 2024-02-07 22:46
As far as I can tell, there is no guardrail against looting an Excess Inventory Target. This is a major omission, probably hidden by most people not looting in their houses or the Payer House LCTN.

**Comment by SteveTownsend** [comment] 2024-02-07 23:23
Cannot reproduce this. I bought the Cottage, blacklisted a barrel and it does not get looted
_2024-02-07 18:01:49.527     info 166128 Barrel/0x1b019f58 added to BlackList_
Taking this out of milestone in case user has more to add.

**Comment by SteveTownsend** [comment] 2024-03-21 12:58
This is probably buggy Blacklist handling, resolving vs 5.6.0.

**Closed by SteveTownsend** 2024-03-21 12:58 UTC
